# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install C libraries
      run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libgl1-mesa-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
        cache-dependency-path: src/go.sum
        
    - name: Install dependencies
      working-directory: ./src
      run: go mod download

    - name: Build
      working-directory: ./src
      run: go build -ldflags="-extld=g++" -v ./...

    - name: Test
      working-directory: ./src
      run: go test -ldflags="-extld=g++" -v ./...
